### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by 3073** [BGluth/Pi-Pedestrian-Counter#1]
We are still using a computer with the RPi.   if I install and setup all the things on the pi ( software ) and load the code on the RPi ( the code that i write in my laptop for counting the people), can I unplug the RPi from the computer ( monitor and keyboard) and install the pi  with its own power source in the place where i  planned to count people like meeting hall, building gate etc ?

**Comment by BGluth** [comment]
Hey 3073. Sorry I took so long to get back to you.

Yeah so once you have the software set up the way your want you can just have it connected to a power source with no monitor or keyboard. If the location also has a reliable WiFi connection then you can remotely manage and monitor the pie which is nice to be able to do.

It's been a long while since I worked on this project but let me know if you have any other questions.

**Comment by 3073** [comment]
@BGluth thank you
